WebApp/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;

namespace WebApp.Models
{
    public class PagingInfo 
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

WebApp/Models/StorageViewModel.cs
using Models.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models
{
    public class StorageViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public IEnumerable<Supplier> Suppliers { get; set; }
        public string SupplierFilter { get; set; }
        public string ExpirationFilter { get; set; }
    }
}

WebApp/Controllers/PriemkaModeController.cs
using Models.Abstract;
using Models.Context;
using Models.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class PriemkaModeController : Controller
    {
        // GET: PriemkaMode
        private Iproduct products;

        public PriemkaModeController(Iproduct products)
        {
            this.products = products;
        }
        public ViewResult Priemka()
        {
            return View(products.Products);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                using (var context = new StoreDBContext())
                {
                    context.Products.Add(product);
                    context.SaveChanges();    
                }

                return RedirectToAction("Priemka");
            }
            return View(product);
        }
    }
}

WebApp/Controllers/StorageController.cs
using Models.Abstract;
using Models.Context;
using Models.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class StorageController : Controller
    {
        private Iproduct products;
        public int max_products = 2;

        public StorageController(Iproduct products)
        {
            this.products = products;
        }

        // GET: Storage
        public ActionResult Storage(string supplierName = "Все", string expirationFilter = "Все", int page = 1)
        {
            var query = products.Products.AsQueryable();

            // Фильтрация по поставщику
            if (supplierName != "Все")
            {
                query = query.Where(p => p.Supplier.Supplier_name == supplierName);
            }

            // Фильтрация по сроку годности
            if (expirationFilter == "Заканчивается через неделю")
            {
                var weekFromNow = DateTime.Now.AddDays(7);
                query = query.Where(p => p.Expiration_date <= weekFromNow && p.Expiration_date >= DateTime.Now);
            }

           
            var viewModel = new StorageViewModel
            {
                Products = query.OrderBy(p => p.Product_price)
                               .Skip((page - 1) * max_products)
                               .Take(max_products),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = max_products,
                    TotalItems = query.Count()
                },
                SupplierFilter = supplierName,
                ExpirationFilter = expirationFilter, // Добавляем новый фильтр
                Suppliers = products.Products
                                    .Select(p => p.Supplier)
                                    .Distinct()
                                    .ToList() // Инициализация списка поставщиков
            };

            return View(viewModel);
        }

    }



}

WebApp/Views/PriemkaMode/Create.cshtml
@model Models.Models.Product

@{
    Layout = null;
    ViewBag.Title = "Приёмка";
}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h2 class="text-center">Приём</h2>

        @using (Html.BeginForm("Create", "PriemkaMode", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(model => model.Product_name, new { @class = "font-weight-bold" })
                @Html.TextBoxFor(model => model.Product_name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Product_name, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Product_price, new { @class = "font-weight-bold" })
                @Html.TextBoxFor(model => model.Product_price, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Product_price, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Count_at_storage, new { @class = "font-weight-bold" })
                @Html.TextBoxFor(model => model.Count_at_storage, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Count_at_storage, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Expiration_date, new { @class = "font-weight-bold" })
                @Html.TextBoxFor(model => model.Expiration_date, new { @class = "form-control", type = "date" })
                @Html.ValidationMessageFor(model => model.Expiration_date, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Supplier_id, new { @class = "font-weight-bold" })
                @Html.TextBoxFor(model => model.Supplier_id, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Supplier_id, "", new { @class = "text-danger" })
            </div>

            <div class="form-group text-center">
                <button type="submit" class="btn btn-primary">Принять</button>
            </div>
        }

        <div class="form-group text-center mt-3">
            <a href="@Url.Action("Priemka", "PriemkaMode")" class="btn btn-secondary">Назад к списку</a>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

WebApp/Views/PriemkaMode/Priemka.cshtml
@model IEnumerable<Models.Models.Product>

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_PriemkaLay.cshtml";
}

<div class="panel panel-default>
    <div class="panel-body">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Product_name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Product_price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Count_at_storage)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Expiration_date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Supplier_id)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Product_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Product_price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Count_at_storage)
                    </td>
                    <td>
                        @item.Expiration_date.ToString("dd/MM/yyyy")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Supplier_id)
                    </td>
                    @*<td>
                            @using (Html.BeginForm("Delete", "Product", new { id = item.Product_id }, FormMethod.Post))
                            {
                                <input type="submit" value="Delete" class="btn btn-default" />
                            }
                        </td>*@
                </tr>

            }
        </table>
    </div>
    <span>
        <div class="panel-footer d-flex justify-content-start">
            <div class="mr-2">
                @Html.ActionLink("Принять товар", "Create", "PriemkaMode", new { @class = "btn btn-default" })
            </div>
            <div>
                <a href="@Url.Action("Storage", "Storage")" class="btn btn-default">Назад к складу</a>
            </div>
        </div>
    </span>
</div>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">My ASP.NET Application</a>
    </div>

    <div>
        <div id="categ" class="col-xs-3"></div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>

WebApp/Views/Shared/_PriemkaLay.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
        <div>
            @RenderBody()
        </div>
</body>
</html>

WebApp/Views/Shared/_Storage.cshtml
@model Models.Models.Product

<div class="well">
    <div class="row">
        <div class="col-xs-10">
            <h3>
                <strong>@Model.Product_name</strong>
            </h3>
            <h4>
                <strong>Срок годности: @Model.Expiration_date.ToString("dd/MM/yyyy")</strong>
            </h4>
            <h4>
                <strong>Поставщик: @Model.Supplier.Supplier_name</strong>
            </h4>
        </div>
        <div class="col-xs-2">
            <h3>
                <strong class="pull-right label label-primary">@Model.Product_price.ToString("# руб")</strong>
            </h3>
        </div>
    </div>
    <div>
        <span>

        </span>
    </div>
</div>

WebApp/Views/Storage/Storage.cshtml
@using Models.Models
@model WebApp.Models.StorageViewModel

<div class="container mt-5">
    <h2>Storage</h2>

    <form method="get" action="@Url.Action("Storage", "Storage")">
        <div class="form-group">
            <label for="supplierName">Фильтр по поставщику</label>
            <select name="supplierName" id="supplierName" class="form-control">
                <option value="Все" @(Model.SupplierFilter == "Все" ? "selected" : "")>Все</option>
                @foreach (var supplier in Model.Suppliers)
                {
                    <option value="@supplier.Supplier_name" @(Model.SupplierFilter == supplier.Supplier_name ? "selected" : "")>@supplier.Supplier_name</option>
                }
            </select>
        </div>

        <div class="form-group">
            <label for="expirationFilter">Фильтр по сроку годности</label>
            <select name="expirationFilter" id="expirationFilter" class="form-control">
                <option value="Все" @(Model.ExpirationFilter == "Все" ? "selected" : "")>Все</option>
                <option value="Заканчивается через неделю" @(Model.ExpirationFilter == "Заканчивается через неделю" ? "selected" : "")>Заканчивается через неделю</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Применить фильтр</button>
    </form>

    <div class="row">
        @foreach (var product in Model.Products)
        {
            @Html.Partial("_Storage", product)
        }
    </div>

    <div class="btn-group pull-right">
        @Html.PageLinks(Model.PagingInfo, x => Url.Action("Storage", new { page = x, supplierName = Model.SupplierFilter }))
    </div>
</div>